CREATE TABLE
  "event" (
    "event_id" UUID NOT NULL,
    "workflow_execution_id" UUID NOT NULL,
    "type" VARCHAR(64) NOT NULL, -- WORKFLOW_EXECUTION_STARTED | WORKFLOW_EXECUTION_COMPLETED | WORKFLOW_EXECUTION_FAILED | WORKFLOW_EXECUTION_CANCELLED | ACTIVITY_TASK_SCHEDULED | ACTIVITY_TASK_STARTED | ACTIVITY_TASK_COMPLETED | ACTIVITY_TASK_FAILED | ACTIVITY_TASK_CANCELLED
    "payload" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("event_id"),
    FOREIGN KEY ("workflow_execution_id") REFERENCES "workflow_execution" ("workflow_execution_id")
  );
