[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
postgresql = { path = "../../external/postgresql" }
tokio = { workspace = true }
uuid = { workspace = true }
